if(WIN32)
  if(MSVC)
    if(MSVC_SHARED_RT)
      set(MSVC_RT_LINK "/MD")
    else()
      set(MSVC_RT_LINK "/MT")
    endif()
    set(CMAKE_CXX_FLAGS_DEBUG_INIT "/D_DEBUG ${MSVC_RT_LINK}d /Zi /Ob0 /Od /RTC1")
    set(CMAKE_CXX_FLAGS_MINSIZEREL_INIT     "${MSVC_RT_LINK} /O1 /Ob1 /D NDEBUG")
    set(CMAKE_CXX_FLAGS_RELEASE_INIT        "${MSVC_RT_LINK} /O2 /Ob2 /D NDEBUG")
    set(CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT "${MSVC_RT_LINK} /Zi /Od /Ob1 /D NDEBUG")
  elseif(MINGW)
    set(CMAKE_CXX_FLAGS_RELEASE_INIT "-D_MT -O3 -DNDEBUG")
  else()
    set(CMAKE_CXX_FLAGS_RELEASE_INIT "-D_MT -O3 -DNDEBUG")
    set(CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS} "-Wno-error=deprecated-declarations")
  endif()
endif()
